import { Globe, MapPin } from "lucide-react";
import { InteractiveGlobe } from "@/components/Canvas/InteractiveGlobe";
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function TheBodyPublicPage() {
    // Fetch published journey entries
    const journeys = await prisma.journeyEntry.findMany({
        where: { status: "PUBLISHED" },
        orderBy: { journeyDate: 'desc' },
    });

    const globeData = journeys.filter(j => j.latitude && j.longitude).map(j => ({
        lat: j.latitude,
        lng: j.longitude,
        size: 0.5,
        color: '#00f0ff',
        name: j.title || "Unknown Location"
    }));

    return (
        <div className="flex flex-col min-h-screen pt-24 pb-12 px-6 lg:px-12 bg-engine-background text-white">
            <div className="max-w-6xl mx-auto w-full">
                <div className="mb-12 border-b border-white/10 pb-8 flex items-center justify-between">
                    <div>
                        <h1 className="text-4xl md:text-5xl font-display font-bold text-white mb-4">
                            The Body
                        </h1>
                        <p className="text-xl text-green-500 font-mono mb-6 max-w-2xl">
                            // THE_TRAVELER
                        </p>
                        <p className="text-lg text-gray-300 max-w-3xl leading-relaxed">
                            A physical record of the journey. For the past 8 years crossing the Americas by motorcycle and van, every step is mapped. These chronicles are generated by AI from raw travel logs.
                        </p>
                    </div>
                    <Globe size={64} className="text-green-500/20" />
                </div>

                <div className="mb-16">
                    <InteractiveGlobe journeyData={globeData} />
                </div>

                <div className="space-y-6">
                    <h2 className="text-2xl font-bold font-display flex items-center gap-2 mb-8">
                        <MapPin className="text-green-500" /> Recent Chronicles
                    </h2>
                    
                    {journeys.length > 0 ? (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 relative z-10">
                            {journeys.map((j) => (
                                <div key={j.id} className="p-6 bg-black/40 border border-white/10 rounded-xl hover:border-green-500/50 transition-colors backdrop-blur-md">
                                    <div className="flex justify-between items-start mb-4">
                                        <h3 className="text-xl font-bold text-white">{j.title || "Raw Entry"}</h3>
                                        <span className="text-xs font-mono text-gray-500">
                                            {j.journeyDate ? j.journeyDate.toLocaleDateString() : "Unknown Date"}
                                        </span>
                                    </div>
                                    <p className="text-gray-400 text-sm mb-4 line-clamp-3">
                                        {j.aiContent || j.rawInput}
                                    </p>
                                    <div className="flex items-center gap-2 text-xs text-green-500 font-mono">
                                        <MapPin size={12} /> {j.location || "Coordinates locked"} 
                                        {j.latitude && j.longitude && ` [${j.latitude.toFixed(2)}, ${j.longitude.toFixed(2)}]`}
                                    </div>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="border border-dashed border-white/10 p-12 text-center rounded-xl bg-black/20 text-gray-400 font-mono">
                            No active telemetry data found.
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
