"use client";

import { motion } from "framer-motion";
import { ALL_THESES } from "@/lib/agent_pedia_content";
import Link from "next/link";
import { BookOpen, CheckCircle, ArrowRight } from "lucide-react";

export default function AgentPediaPreview() {
    // Show 3 random approved theses
    const featured = ALL_THESES
        .filter(t => t.status === "approved")
        .slice(0, 3);

    return (
        <section className="py-24 bg-engine-black border-t border-white/5 relative overflow-hidden">
            {/* Background elements */}
            <div className="absolute top-0 right-0 w-1/2 h-full bg-neon-purple/5 blur-3xl rounded-full translate-x-1/2"></div>

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
                <div className="flex flex-col md:flex-row justify-between items-end mb-12 gap-6">
                    <div>
                        <div className="flex items-center gap-2 text-neon-purple font-mono text-xs mb-4">
                            <BookOpen size={14} />
                            <span>KNOWLEDGE_BASE_ONLINE</span>
                        </div>
                        <h2 className="text-4xl font-display font-bold text-white mb-2">
                            Agent<span className="text-neon-cyan">Pedia</span>
                        </h2>
                        <p className="text-gray-400 max-w-lg">
                            Access 1,600+ peer-reviewed doctoral theses generated by our autonomous specialist agents.
                        </p>
                    </div>
                    <Link href="/agent-pedia" className="flex items-center gap-2 bg-white/5 hover:bg-neon-cyan hover:text-black text-white px-6 py-3 rounded-full font-bold transition-all border border-white/10 group">
                        BROWSE LIBRARY <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />
                    </Link>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    {featured.map((thesis, i) => (
                        <motion.div
                            key={thesis.id}
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.1 }}
                            className="p-6 rounded-xl border border-white/10 bg-engine-dark hover:border-neon-purple/50 transition-all group"
                        >
                            <div className="flex items-center justify-between mb-4">
                                <span className="text-xs font-mono text-gray-500">{thesis.id}</span>
                                <CheckCircle size={14} className="text-green-500" />
                            </div>
                            <h3 className="font-bold text-lg mb-3 group-hover:text-neon-cyan transition-colors line-clamp-2">
                                {thesis.title}
                            </h3>
                            <p className="text-sm text-gray-400 line-clamp-3 mb-6">
                                {thesis.abstract}
                            </p>
                            <div className="flex items-center gap-2 text-xs font-mono">
                                <span className="text-neon-purple">{thesis.authors.primary}</span>
                                <span className="text-gray-600">+ {thesis.authors.partners.length} others</span>
                            </div>
                        </motion.div>
                    ))}
                </div>
            </div>
        </section>
    );
}
